import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './navbar'
import LayoutSidemenu from './layoutSidemenu'
import LayoutBreadcrumb from './layoutBreadcrumb'
import LoginForm from './login'
import 'bootstrap/dist/css/bootstrap.min.css'
import './encircle.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>      
        <Navbar />
        <div className="container">
          <div className="row pt-2">
            <div className="col-2">
              <LayoutSidemenu />
            </div>
            <div className="col-10">
              <LayoutBreadcrumb />
              <main>
                {children}
              </main>
            </div>
          </div>
        </div>
        <LoginForm />
      </body>
    </html>
  )
}
